"""Reconcile observed browser controls, content, and network evidence."""
from __future__ import annotations

import re
from pathlib import Path
from typing import Any
from .files import (
    file_sha256,
    file_url_path,
    load_json_file,
    resolve_path,
)
from .hard_common import (
    get_path,
    live_signal_is_substantive,
    meaningful_tokens,
    normalized,
    parse_timestamp,
)
from .source import (
    decode_resource_body,
    scan_forbidden_content,
    selector_is_overbroad,
    selector_specs,
    sniff_image_type,
)


def live_control_key(control: Any) -> tuple[str, str] | None:
    if not isinstance(control, dict):
        return None
    selector = control.get("selector")
    name = control.get("accessible_name") or control.get("label")
    if not isinstance(selector, str) or not isinstance(name, str):
        return None
    selector = selector.strip()
    name = normalized(name)
    if not selector or not name:
        return None
    return selector, name


def validate_live_audit_bundle(
    bundle: dict[str, Any] | None,
    config: dict[str, Any] | None,
    config_path: Path | None,
    data: dict[str, Any],
    base_dir: Path,
    source_fingerprint: str | None,
    captures: dict[Path, dict[str, Any]],
    errors: list[str],
) -> None:
    if bundle is None or config is None or config_path is None:
        return
    expected_file_entry = file_url_path(config.get("entry_url"), config_path.parent)
    expected_file_url = expected_file_entry.as_uri() if expected_file_entry is not None else None
    if bundle.get("schema_version") != 1 or bundle.get("generated_by") != "genscaff-live-audit-v1":
        errors.append("Live audit bundle has an invalid schema or generator")
    if not re.fullmatch(
        r"[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}",
        str(bundle.get("run_id", "")),
    ):
        errors.append("Live audit bundle.run_id must be a UUID generated by the runner")
    started = parse_timestamp(bundle.get("started_at"), "live_audit.started_at", errors)
    completed = parse_timestamp(bundle.get("completed_at"), "live_audit.completed_at", errors)
    if started is not None and completed is not None and completed <= started:
        errors.append("Live audit completed_at must be after started_at")
    if source_fingerprint and bundle.get("source_fingerprint") != source_fingerprint:
        errors.append("Live audit bundle source_fingerprint does not match the scanned source tree")

    expected_runner = Path(__file__).resolve().parent.parent / "live_audit.js"
    runner_info = bundle.get("runner")
    if not isinstance(runner_info, dict):
        errors.append("Live audit bundle is missing runner provenance")
    else:
        try:
            actual_runner = Path(str(runner_info.get("path", ""))).resolve()
        except OSError:
            actual_runner = Path()
        if actual_runner != expected_runner:
            errors.append("Live audit must be produced by the bundled gate-owned runner")
        if runner_info.get("sha256") != file_sha256(expected_runner):
            errors.append("Live audit runner sha256 does not match the bundled runner")
    config_info = bundle.get("config")
    if not isinstance(config_info, dict):
        errors.append("Live audit bundle is missing config provenance")
    else:
        try:
            actual_config = Path(str(config_info.get("path", ""))).resolve()
        except OSError:
            actual_config = Path()
        if actual_config != config_path.resolve():
            errors.append("Live audit config path does not match implementation_audit.live_audit_config")
        if config_info.get("sha256") != file_sha256(config_path):
            errors.append("Live audit config sha256 does not match the executed config")
    browser = bundle.get("browser")
    if not isinstance(browser, dict) or browser.get("engine") != "chromium":
        errors.append("Live audit must use a fresh Chromium browser context")
    elif not isinstance(browser.get("version"), str) or not re.match(r"^\d+\.", browser["version"]):
        errors.append("Live audit bundle is missing a Chromium version")

    counts = bundle.get("prohibited_finding_counts")
    required_count_fields = {
        "computed_style",
        "svg",
        "canvas_gradient",
        "data_uri",
        "loaded_resource",
    }
    if not isinstance(counts, dict) or set(counts) != required_count_fields:
        errors.append("Live audit prohibited_finding_counts is incomplete")
    else:
        for field in sorted(required_count_fields):
            if counts.get(field) != 0:
                errors.append(f"Live audit found prohibited {field} output: {counts.get(field)}")

    report_signal_selectors = [
        item.get("selector", "").strip()
        for item in get_path(data, "product_specificity.domain_signals", [])
        if isinstance(item, dict) and isinstance(item.get("selector"), str)
    ]
    report_decision_selectors = [
        item.get("selector", "").strip()
        for item in get_path(data, "product_specificity.decision_points", [])
        if isinstance(item, dict) and isinstance(item.get("selector"), str)
    ]
    config_signal_selectors = selector_specs(config.get("domain_signal_selectors"))
    config_decision_selectors = selector_specs(config.get("decision_selectors"))
    if len(report_signal_selectors) != len(set(report_signal_selectors)):
        errors.append("product_specificity.domain_signals selectors must be unique")
    if len(report_decision_selectors) != len(set(report_decision_selectors)):
        errors.append("product_specificity.decision_points selectors must be unique")
    if set(report_signal_selectors) & set(report_decision_selectors):
        errors.append("Domain and decision evidence must use distinct selectors")
    if len(config_signal_selectors) != len(set(config_signal_selectors)):
        errors.append("live_audit_config.domain_signal_selectors must be unique")
    if len(config_decision_selectors) != len(set(config_decision_selectors)):
        errors.append("live_audit_config.decision_selectors must be unique")
    for selector in report_signal_selectors + report_decision_selectors:
        if selector_is_overbroad(selector):
            errors.append(f"Product evidence selector is an overbroad application container: {selector}")
    if set(config_signal_selectors) != set(report_signal_selectors) or len(config_signal_selectors) != len(report_signal_selectors):
        errors.append("live_audit_config domain selectors must exactly match report domain signals")
    if set(config_decision_selectors) != set(report_decision_selectors) or len(config_decision_selectors) != len(report_decision_selectors):
        errors.append("live_audit_config decision selectors must exactly match report decision points")

    report_controls = get_path(data, "action_trace.control_inventory", [])
    report_control_keys: set[tuple[str, str]] = set()
    report_by_selector: dict[str, dict[str, Any]] = {}
    for index, control in enumerate(report_controls if isinstance(report_controls, list) else []):
        key = live_control_key(control)
        if key is None:
            errors.append(
                f"action_trace.control_inventory[{index}] needs a selector and accessible_name for live cross-checking"
            )
            continue
        if key in report_control_keys or key[0] in report_by_selector:
            errors.append(f"Duplicate live control identity in action_trace.control_inventory[{index}]")
        report_control_keys.add(key)
        report_by_selector[key[0]] = control

    raw_config_scenarios = config.get("control_scenarios")
    config_scenarios: dict[str, dict[str, Any]] = {}
    if not isinstance(raw_config_scenarios, list):
        errors.append("live_audit_config.control_scenarios must be a list")
        raw_config_scenarios = []
    for index, scenario in enumerate(raw_config_scenarios):
        path = f"live_audit_config.control_scenarios[{index}]"
        if not isinstance(scenario, dict):
            errors.append(f"{path} must be an object")
            continue
        selector = scenario.get("selector")
        if not isinstance(selector, str) or not selector.strip():
            errors.append(f"{path}.selector is required")
            continue
        selector = selector.strip()
        if selector in config_scenarios:
            errors.append(f"{path}.selector is duplicated: {selector}")
        config_scenarios[selector] = scenario
        action = scenario.get("action", "click")
        if action not in {"click", "fill", "select", "check", "press"}:
            errors.append(f"{path}.action is unsupported")
        if action in {"fill", "select"} and not isinstance(scenario.get("value"), str):
            errors.append(f"{path}.value is required for {action}")
        if action == "press" and not isinstance(scenario.get("key"), str):
            errors.append(f"{path}.key is required for press")
        setup = scenario.get("setup", "default")
        if setup not in {"default", "primary-feedback", "primary-terminal"}:
            errors.append(f"{path}.setup is invalid")
        for field in ("expected_selector", "expected_url_pattern", "expected_value"):
            if field in scenario and not isinstance(scenario.get(field), str):
                errors.append(f"{path}.{field} must be a string")
        if "expected_checked" in scenario and not isinstance(scenario.get("expected_checked"), bool):
            errors.append(f"{path}.expected_checked must be boolean")
        if not any(
            field in scenario
            for field in ("expected_selector", "expected_url_pattern", "expected_value", "expected_checked")
        ):
            errors.append(f"{path} needs an observable expected outcome")
        pattern = scenario.get("expected_url_pattern")
        if isinstance(pattern, str):
            try:
                re.compile(pattern)
            except re.error as exc:
                errors.append(f"{path}.expected_url_pattern is invalid: {exc}")

    primary_selector = get_path(config, "primary_flow.selector")
    recovery_selector = get_path(config, "primary_flow.recovery_selector")
    disabled_selectors = {
        selector
        for selector, control in report_by_selector.items()
        if control.get("behavior") == "disabled"
    }
    primary_report = [
        control
        for control in report_by_selector.values()
        if control.get("role") == "primary"
    ]
    if len(primary_report) != 1 or primary_report[0].get("selector") != primary_selector:
        errors.append("Live primary selector must identify the report's sole primary control")
    if recovery_selector not in report_by_selector:
        errors.append("Live recovery selector must be present in action_trace.control_inventory")
    elif report_by_selector[recovery_selector].get("behavior") == "disabled":
        errors.append("Live recovery selector cannot be declared disabled")
    if primary_selector in disabled_selectors:
        errors.append("Live primary selector cannot be declared disabled")

    content_manifest, _ = load_json_file(
        get_path(data, "implementation_audit.content_manifest"),
        base_dir,
        "implementation_audit.content_manifest",
        errors,
    )
    manifest_claims: set[tuple[str, str]] = set()
    if isinstance(content_manifest, dict):
        for item in content_manifest.get("visible_claims", []):
            if isinstance(item, dict) and isinstance(item.get("selector"), str):
                manifest_claims.add((item["selector"].strip(), normalized(item.get("text"))))

    captures_by_checkpoint: dict[tuple[str, str], dict[str, Any]] = {}
    for record in captures.values():
        key = (str(record.get("viewport", "")), str(record.get("checkpoint", "")))
        if key in captures_by_checkpoint:
            errors.append(f"Capture manifest repeats live checkpoint {key}")
        captures_by_checkpoint[key] = record

    viewports = bundle.get("viewports")
    if not isinstance(viewports, list):
        errors.append("Live audit bundle.viewports must be a list")
        return
    viewport_names = [item.get("name") for item in viewports if isinstance(item, dict)]
    if set(viewport_names) != {"desktop", "mobile"} or len(viewport_names) != 2:
        errors.append("Live audit must contain exactly one desktop and one mobile viewport")

    all_live_claims: set[tuple[str, str]] = set()
    for viewport in viewports:
        if not isinstance(viewport, dict):
            errors.append("Live audit viewport must be an object")
            continue
        name = viewport.get("name")
        width = viewport.get("width")
        if expected_file_url is not None and viewport.get("default_route_url") != expected_file_url:
            errors.append(f"Live {name} default route does not match the canonical file entry")
        if name == "desktop" and (isinstance(width, bool) or not isinstance(width, int) or width < 1024):
            errors.append("Live desktop viewport must be at least 1024 CSS pixels wide")
        if name == "mobile" and (isinstance(width, bool) or not isinstance(width, int) or not 320 <= width <= 480):
            errors.append("Live mobile viewport must be between 320 and 480 CSS pixels wide")
        for category, values in (viewport.get("errors") or {}).items():
            if not isinstance(values, list) or values:
                errors.append(f"Live {name} browser {category} errors must be an empty list")
        for field in ("computed_style_findings", "svg_findings", "canvas_gradient_calls"):
            values = viewport.get(field)
            if not isinstance(values, list) or values:
                errors.append(f"Live {name} {field} must be an empty list")
        for uri in viewport.get("data_uris", []) if isinstance(viewport.get("data_uris"), list) else []:
            if not isinstance(uri, dict) or uri.get("decode_error") or uri.get("truncated") is True or uri.get("scan_findings"):
                errors.append(f"Live {name} data URI was undecodable, truncated, or prohibited")
        viewport_claims = viewport.get("claim_candidates")
        if not isinstance(viewport_claims, list):
            errors.append(f"Live {name} claim_candidates must be a list")
        else:
            for claim in viewport_claims:
                if isinstance(claim, dict):
                    all_live_claims.add(
                        (str(claim.get("selector", "")).strip(), normalized(claim.get("text")))
                    )

        resources = viewport.get("first_party_resources")
        if not isinstance(resources, list) or not resources:
            errors.append(f"Live {name} audit must hash at least one loaded first-party resource")
        else:
            for resource in resources:
                if not isinstance(resource, dict):
                    errors.append(f"Live {name} first-party resource record is invalid")
                    continue
                if resource.get("first_party") is not True:
                    errors.append(f"Live {name} first-party resource classification is invalid")
                status = resource.get("status")
                if isinstance(status, bool) or not isinstance(status, int) or not 200 <= status < 400:
                    errors.append(f"Live {name} first-party resource returned an invalid status: {resource.get('url')}")
                elif 300 <= status < 400 and (
                    resource.get("redirect") is not True
                    or not isinstance(resource.get("redirect_location"), str)
                    or not resource.get("redirect_location")
                    or resource.get("byte_length") != 0
                ):
                    errors.append(f"Live {name} first-party redirect evidence is incomplete: {resource.get('url')}")
                if resource.get("body_error"):
                    errors.append(f"Live {name} first-party resource body could not be inspected: {resource.get('url')}")
                if not isinstance(resource.get("resource_type"), str) or not resource.get("resource_type"):
                    errors.append(f"Live {name} first-party resource type is missing: {resource.get('url')}")
                payload = decode_resource_body(
                    resource,
                    f"Live {name} first-party resource {resource.get('url')}",
                    errors,
                )
                sniffed_type = sniff_image_type(payload)
                if resource.get("sniffed_type", "") != sniffed_type:
                    errors.append(f"Live {name} first-party resource magic-byte type is inconsistent")
                if payload is not None:
                    scan_forbidden_content(
                        payload.decode("utf-8", errors="replace"),
                        f"loaded first-party resource {resource.get('url')}",
                        errors,
                    )
                if resource.get("body_truncated") is True:
                    errors.append(f"Live {name} first-party resource body cannot be truncated")
                if resource.get("scan_findings"):
                    errors.append(f"Live {name} loaded resource contains a prohibited visual pattern")
                if not re.fullmatch(r"[0-9a-f]{64}", str(resource.get("sha256", ""))):
                    errors.append(f"Live {name} loaded resource is missing a sha256")
                for uri in resource.get("data_uris", []) if isinstance(resource.get("data_uris"), list) else []:
                    if not isinstance(uri, dict) or uri.get("decode_error") or uri.get("truncated") is True or uri.get("scan_findings"):
                        errors.append(f"Live {name} loaded resource contains unsafe data URI evidence")
        external_resources = viewport.get("external_resources")
        if not isinstance(external_resources, list):
            errors.append(f"Live {name} external_resources must be a list")
        else:
            for resource in external_resources:
                if not isinstance(resource, dict):
                    errors.append(f"Live {name} external resource record is invalid")
                    continue
                if resource.get("first_party") is not False:
                    errors.append(f"Live {name} external resource classification is invalid")
                status = resource.get("status")
                if isinstance(status, bool) or not isinstance(status, int) or not 200 <= status < 400:
                    errors.append(f"Live {name} external resource returned an invalid status: {resource.get('url')}")
                elif 300 <= status < 400 and (
                    resource.get("redirect") is not True
                    or not isinstance(resource.get("redirect_location"), str)
                    or not resource.get("redirect_location")
                    or resource.get("byte_length") != 0
                ):
                    errors.append(f"Live {name} external redirect evidence is incomplete: {resource.get('url')}")
                if resource.get("body_error"):
                    errors.append(f"Live {name} external resource body could not be inspected: {resource.get('url')}")
                if not isinstance(resource.get("resource_type"), str) or not resource.get("resource_type"):
                    errors.append(f"Live {name} external resource type is missing: {resource.get('url')}")
                payload = decode_resource_body(
                    resource,
                    f"Live {name} external resource {resource.get('url')}",
                    errors,
                )
                sniffed_type = sniff_image_type(payload)
                if resource.get("sniffed_type", "") != sniffed_type:
                    errors.append(f"Live {name} external resource magic-byte type is inconsistent")
                if payload is not None:
                    scan_forbidden_content(
                        payload.decode("utf-8", errors="replace"),
                        f"loaded external resource {resource.get('url')}",
                        errors,
                    )
                content_type = str(resource.get("content_type", "")).casefold()
                resource_url = str(resource.get("url", ""))
                raster_types = {
                    "image/png", "image/jpeg", "image/gif", "image/webp", "image/avif", "image/bmp"
                }
                declared_raster = bool(
                    re.match(r"^image/(?:png|jpe?g|gif|webp|avif|bmp)", content_type)
                    or re.search(r"\.(?:png|jpe?g|gif|webp|avif|bmp)(?:[?#]|$)", resource_url, re.I)
                )
                uninspectable_visual = resource.get("resource_type") == "image" and not sniffed_type
                if declared_raster or sniffed_type in raster_types or uninspectable_visual:
                    errors.append(
                        f"Live {name} uses an externally mutable raster resource; localize and review it: {resource.get('url')}"
                    )
                if resource.get("body_truncated") is True:
                    errors.append(f"Live {name} external resource body cannot be truncated")
                if resource.get("scan_findings"):
                    errors.append(f"Live {name} external resource contains a prohibited visual pattern")
                if not re.fullmatch(r"[0-9a-f]{64}", str(resource.get("sha256", ""))):
                    errors.append(f"Live {name} external resource is missing a sha256")
                for uri in resource.get("data_uris", []) if isinstance(resource.get("data_uris"), list) else []:
                    if not isinstance(uri, dict) or uri.get("decode_error") or uri.get("truncated") is True or uri.get("scan_findings"):
                        errors.append(f"Live {name} external resource contains unsafe data URI evidence")

        signals = viewport.get("domain_signals")
        signal_identities: list[str] = []
        if (
            not isinstance(signals, list)
            or len(signals) != len(report_signal_selectors)
            or {item.get("selector") for item in signals if isinstance(item, dict)} != set(report_signal_selectors)
        ):
            errors.append(f"Live {name} domain signal inventory does not match the report")
        else:
            report_lookup = {
                item["selector"]: item
                for item in get_path(data, "product_specificity.domain_signals", [])
                if isinstance(item, dict) and isinstance(item.get("selector"), str)
            }
            for signal in signals:
                matches = signal.get("matches")
                if signal.get("count") != 1 or not isinstance(matches, list) or len(matches) != 1 or matches[0].get("visible") is not True:
                    errors.append(f"Live {name} domain selector must resolve to exactly one visible element: {signal.get('selector')}")
                    continue
                identity = matches[0].get("element_identity")
                if not isinstance(identity, str) or not identity:
                    errors.append(f"Live {name} domain selector lacks a stable element identity: {signal.get('selector')}")
                elif selector_is_overbroad(identity) or identity.casefold().endswith(" > main"):
                    errors.append(f"Live {name} domain selector resolves to an overbroad application container")
                else:
                    signal_identities.append(identity)
                if not live_signal_is_substantive(matches[0]):
                    errors.append(f"Live {name} domain selector is visually concealed or trivial: {signal.get('selector')}")
                visible_tokens = meaningful_tokens(matches[0].get("text"))
                detail_tokens = meaningful_tokens(report_lookup[signal["selector"]].get("domain_detail"))
                if not visible_tokens & detail_tokens:
                    errors.append(f"Live {name} domain selector text does not substantiate its report detail: {signal.get('selector')}")

        decisions = viewport.get("decision_signals")
        decision_identities: list[str] = []
        if (
            not isinstance(decisions, list)
            or len(decisions) != len(report_decision_selectors)
            or {item.get("selector") for item in decisions if isinstance(item, dict)} != set(report_decision_selectors)
        ):
            errors.append(f"Live {name} decision signal inventory does not match the report")
        else:
            report_lookup = {
                item["selector"]: item
                for item in get_path(data, "product_specificity.decision_points", [])
                if isinstance(item, dict) and isinstance(item.get("selector"), str)
            }
            for signal in decisions:
                matches = signal.get("matches")
                if signal.get("count") != 1 or not isinstance(matches, list) or len(matches) != 1 or matches[0].get("visible") is not True:
                    errors.append(f"Live {name} decision selector must resolve to exactly one visible element: {signal.get('selector')}")
                    continue
                identity = matches[0].get("element_identity")
                if not isinstance(identity, str) or not identity:
                    errors.append(f"Live {name} decision selector lacks a stable element identity: {signal.get('selector')}")
                elif selector_is_overbroad(identity) or identity.casefold().endswith(" > main"):
                    errors.append(f"Live {name} decision selector resolves to an overbroad application container")
                else:
                    decision_identities.append(identity)
                if not live_signal_is_substantive(matches[0]):
                    errors.append(f"Live {name} decision selector is visually concealed or trivial: {signal.get('selector')}")
                report_item = report_lookup[signal["selector"]]
                expected_tokens = meaningful_tokens(report_item.get("inputs")) | meaningful_tokens(report_item.get("consequence"))
                if len(meaningful_tokens(matches[0].get("text")) & expected_tokens) < 2:
                    errors.append(f"Live {name} decision selector text does not substantiate its inputs and consequence")
        combined_signal_identities = signal_identities + decision_identities
        if len(combined_signal_identities) != len(set(combined_signal_identities)):
            errors.append(f"Live {name} product and decision selectors collapse onto the same DOM element")

        flow = viewport.get("primary_flow")
        if not isinstance(flow, dict):
            errors.append(f"Live {name} primary_flow is missing")
            continue
        if flow.get("selector") != primary_selector or flow.get("recovery_selector") != recovery_selector:
            errors.append(f"Live {name} primary flow selectors differ from the executed config")
        if flow.get("ordered_stages") != ["start", "feedback", "terminal", "recovery"]:
            errors.append(f"Live {name} primary flow must preserve start→feedback→terminal→recovery")
        states = flow.get("states")
        if not isinstance(states, list) or len(states) != 4:
            errors.append(f"Live {name} primary flow must contain four captured states")
            continue
        if expected_file_entry is not None:
            start_path = file_url_path(states[0].get("url"), config_path.parent)
            if start_path != expected_file_entry:
                errors.append(
                    f"Live {name} start state redirected away from the canonical project index"
                )
            start_frames = states[0].get("frames") if isinstance(states[0], dict) else None
            if (
                not isinstance(start_frames, list)
                or not start_frames
                or file_url_path(start_frames[0].get("frame_url"), config_path.parent) != expected_file_entry
            ):
                errors.append(f"Live {name} top frame is not the canonical project index")
        screenshot_hashes: list[str] = []
        dom_hashes: list[str] = []
        text_hashes: list[str] = []
        for state in states:
            if not isinstance(state, dict):
                errors.append(f"Live {name} primary state is invalid")
                continue
            stage = state.get("stage")
            screenshot_hash = state.get("screenshot_sha256")
            screenshot_hashes.append(str(screenshot_hash))
            dom_hashes.append(str(state.get("dom_sha256")))
            text_hashes.append(str(state.get("visible_text_sha256")))
            live_path = resolve_path(
                state.get("screenshot_path"),
                config_path.parent,
                f"live_audit.{name}.{stage}.screenshot_path",
                errors,
            )
            record = captures_by_checkpoint.get((str(name), f"primary-{stage}"))
            if record is None:
                errors.append(f"Capture manifest is missing live {name} primary-{stage}")
            elif live_path != record.get("_artifact") or screenshot_hash != record.get("sha256"):
                errors.append(f"Live {name} primary-{stage} screenshot does not match the capture manifest")
            visible_text = state.get("visible_text")
            if not isinstance(visible_text, str) or len(visible_text.strip()) < 120:
                errors.append(f"Live {name} {stage} visible text is too thin for product validation")
        if len(set(screenshot_hashes)) != 4 or len(set(dom_hashes)) != 4 or len(set(text_hashes)) != 4:
            errors.append(f"Live {name} primary flow states must have distinct screenshot, DOM, and visible-text hashes")
        start_text = states[0].get("visible_text", "") if isinstance(states[0], dict) else ""
        visible_tokens = meaningful_tokens(start_text)
        contract_tokens = meaningful_tokens(get_path(data, "context.product_type")) | meaningful_tokens(get_path(data, "context.primary_task"))
        for domain_object in get_path(data, "context.domain_objects", []) or []:
            object_tokens = meaningful_tokens(domain_object)
            contract_tokens.update(object_tokens)
            if object_tokens and not object_tokens & visible_tokens:
                errors.append(f"Live {name} default route omits domain object: {domain_object}")
        if len(visible_tokens & contract_tokens) < min(6, len(contract_tokens)):
            errors.append(f"Live {name} default route does not expose enough product-contract vocabulary")

        actual_controls = viewport.get("controls")
        actual_keys: set[tuple[str, str]] = set()
        if not isinstance(actual_controls, list):
            errors.append(f"Live {name} controls must be a list")
        else:
            for control in actual_controls:
                key = live_control_key(control)
                if key is None:
                    errors.append(f"Live {name} control lacks a stable selector or accessible name")
                    continue
                if key in actual_keys:
                    errors.append(f"Live {name} control identity is duplicated: {key[0]}")
                actual_keys.add(key)
                if not isinstance(control.get("disabled"), bool):
                    errors.append(f"Live {name} control disabled state is missing: {key[0]}")
                reported_behavior = report_by_selector.get(key[0], {}).get("behavior")
                if control.get("disabled") is True and reported_behavior != "disabled":
                    errors.append(f"Live {name} control is unexpectedly disabled: {key[0]}")
                if reported_behavior == "disabled" and control.get("disabled") is not True:
                    errors.append(f"Live {name} control is declared disabled but remains actionable: {key[0]}")
                href = str(control.get("href", "")).strip().casefold()
                if href == "#" or href.startswith("javascript:"):
                    errors.append(f"Live {name} control has a dead placeholder href: {key[0]}")
        if actual_keys != report_control_keys:
            missing = sorted(report_control_keys - actual_keys)
            unreported = sorted(actual_keys - report_control_keys)
            errors.append(f"Live {name} control inventory differs from report; missing={missing}, unreported={unreported}")

        scenario_selectors = set(config_scenarios)
        extra_selectors = (
            {key[0] for key in actual_keys}
            - {str(primary_selector), str(recovery_selector)}
            - disabled_selectors
        )
        if scenario_selectors != extra_selectors:
            errors.append(
                f"Live {name} actionable non-primary controls need exact fresh-context scenarios; "
                f"expected={sorted(extra_selectors)}, configured={sorted(scenario_selectors)}"
            )
        scenarios = viewport.get("control_scenarios")
        result_selectors = {
            item.get("selector") for item in scenarios if isinstance(item, dict)
        } if isinstance(scenarios, list) else set()
        if not isinstance(scenarios, list) or result_selectors != extra_selectors or len(scenarios) != len(extra_selectors):
            errors.append(f"Live {name} control scenario results are incomplete or duplicated")
        else:
            for scenario in scenarios:
                selector = scenario.get("selector")
                spec = config_scenarios.get(selector, {})
                expected_public = {
                    "action": spec.get("action", "click"),
                    "setup": spec.get("setup", "default"),
                    "value": spec.get("value"),
                    "key": spec.get("key"),
                    "expected_selector": spec.get("expected_selector", ""),
                    "expected_url_pattern": spec.get("expected_url_pattern", ""),
                    "expected_value": spec.get("expected_value"),
                    "expected_checked": spec.get("expected_checked"),
                }
                for field, expected in expected_public.items():
                    if scenario.get(field) != expected:
                        errors.append(
                            f"Live {name} control scenario {selector} does not match config field {field}"
                        )
                if scenario.get("matched_count") != 1:
                    errors.append(f"Live {name} control scenario must target exactly one element: {selector}")
                if scenario.get("disabled") is not False:
                    errors.append(f"Live {name} control scenario target is disabled or unverified: {selector}")
                if (
                    isinstance(scenario.get("async_activity_marker"), bool)
                    or not isinstance(scenario.get("async_activity_marker"), int)
                ):
                    errors.append(f"Live {name} control scenario lacks an async activity marker: {selector}")
                if not isinstance(scenario.get("pending_action_async"), list) or scenario.get("pending_action_async"):
                    errors.append(f"Live {name} control scenario left unsettled async work: {selector}")
                if scenario.get("passed") is not True or scenario.get("error"):
                    errors.append(f"Live {name} control scenario failed: {selector}")
                before = scenario.get("before") if isinstance(scenario.get("before"), dict) else {}
                after = scenario.get("after") if isinstance(scenario.get("after"), dict) else {}
                target_before = (
                    scenario.get("target_state_before")
                    if isinstance(scenario.get("target_state_before"), dict)
                    else {}
                )
                target_after = (
                    scenario.get("target_state_after")
                    if isinstance(scenario.get("target_state_after"), dict)
                    else {}
                )
                document_changed = (
                    before.get("dom_sha256") != after.get("dom_sha256")
                    or before.get("url") != after.get("url")
                    or before.get("visible_text_sha256") != after.get("visible_text_sha256")
                )
                target_changed = (
                    target_before.get("value") != target_after.get("value")
                    or target_before.get("checked") != target_after.get("checked")
                )
                if scenario.get("meaningful_change") is not True or not (document_changed or target_changed):
                    errors.append(f"Live {name} control scenario produced no observable state change: {selector}")
                if spec.get("expected_selector") and (
                    scenario.get("expected_selector_visible_before") is not False
                    or scenario.get("expected_selector_visible_after") is not True
                ):
                    errors.append(f"Live {name} expected selector did not transition for: {selector}")
                if spec.get("expected_url_pattern") and (
                    scenario.get("expected_url_matched_before") is not False
                    or scenario.get("expected_url_matched_after") is not True
                ):
                    errors.append(f"Live {name} expected URL did not transition for: {selector}")
                if "expected_value" in spec and (
                    target_before.get("value") == spec.get("expected_value")
                    or target_after.get("value") != spec.get("expected_value")
                ):
                    errors.append(f"Live {name} expected value was not caused by the action: {selector}")
                if "expected_checked" in spec and (
                    target_before.get("checked") == spec.get("expected_checked")
                    or target_after.get("checked") != spec.get("expected_checked")
                ):
                    errors.append(f"Live {name} expected checked state was not caused by the action: {selector}")

    if all_live_claims != manifest_claims:
        missing = sorted(all_live_claims - manifest_claims)
        stale = sorted(manifest_claims - all_live_claims)
        errors.append(f"Live visible claim inventory differs from content_manifest; missing={missing}, stale={stale}")

    output_dir = resolve_path(config.get("output_dir"), config_path.parent, "live_audit_config.output_dir", errors)
    if output_dir is not None:
        saved_bundle = output_dir / "live-audit-bundle.json"
        if not saved_bundle.is_file():
            errors.append("Gate-owned live audit did not persist live-audit-bundle.json")
